baseURL = "https://blog.s20n.dev"
languageCode = "en-us"
title = "s20n blog"

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = "github.com/shriramters/plague"  # Theme

[params]
  siteHeaderText = "s20n blog"

  colors = "default"
  
  [params.hcard]
    fullName = "Shriram Ravindranathan"
    social = [
      { platform = "github", identity = "shriramters", url_pattern = "https://github.com/%s" },
      { platform = "bluesky", identity = "s20n.dev", url_pattern = "https://bsky.app/profile/%s" }
    ]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
